### ISSUE TITLE
 RuntimeError: fft: ATen not compiled with MKL support

### ISSUE THREAD

**Issue by StuartIanNaylor** [isakbosman/pytorch_arm_builds#1]
I was just experimenting with https://github.com/mechanicalsea/spectra as saw pytorch, torchaudio & vision on armv7 and was like wow lets test something out.

Sort of confused as https://github.com/pytorch/pytorch/issues/24334#issuecomment-568794596 seems to be intel orientated.

https://github.com/pytorch/pytorch/issues/41592

But not worthy as beyond my comprehension

Thanks for the wheels though.

**Comment by jplij** [comment]
Also same error on ppc64el when doing torch.fft.fft.

**Comment by StuartIanNaylor** [comment]
@jplij From reading I don't think there is anything isakbosman can do as MKL is forced and in the main repo the reply has been implement your own non MLK build.
Why vendor libs have perference over standard opensource and then vendor accelerated libs are then optional and supported by vendors or interested is confusing.

Maybe I am wrong but for now it just seems a cul-de-sac.
